default:
  image: ubuntu:latest

deploy-prod:
  only:
    - main
  stage: deploy
  before_script:
    - ls -la
    - pwd
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$(cat $SSH_KEY_EC2)" >> ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - >- 
      ssh -i ~/.ssh/id_rsa root@$EC2_ADDRESS \
      'git config --global --replace-all user.name "vijay-ravi"
      && git config --global --replace-all user.email "vijayravi187@gmail.com"
      '
    - >-
      ssh -i ~/.ssh/id_rsa root@$EC2_ADDRESS \
      '
      cd airflow
      && git status
      && git restore .env
      && git pull --rebase
      && git status
      && sed -i s:%AIRFLOW_UID%:'"$(id -u)"':g .env
      && sed -i s:%AIRFLOW_GID%:0:g .env
      && sed -i s:%_AIRFLOW_WWW_USER_USERNAME%:'"$_AIRFLOW_WWW_USER_USERNAME"':g .env
      && sed -i s:%_AIRFLOW_WWW_USER_PASSWORD%:'"$_AIRFLOW_WWW_USER_PASSWORD"':g .env
      && sed -i s|%AIRFLOW_IMAGE_NAME%|"spaceflow:2.1.2"|g .env
      && docker build . --file Dockerfile --tag spaceflow:2.1.2
      '
    - >-
      ssh -i ~/.ssh/id_rsa root@$EC2_ADDRESS \
      'cd airflow &&
      if [ docker ps | grep -q keyword ]; 
      then docker-compose down && docker-compose up -d --build; 
      else docker-compose up -d --build; 
      fi;'
