name: GitlabSync

on:
  - push
  - delete

jobs:
  build-and-configure-airflow:
    needs: sync
    runs-on: ubuntu-latest
    name: Build and Configure Airflow Docker Image
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag spaceflow:2.1.2
    - name: Update .env file
      run: |
        echo "AIRFLOW_IMAGE_NAME=spaceflow:2.1.2" >> .env
    - name: Commit and Push .env Changes
      run: |
        git config --global user.email "vijayravi187@gmail.com"
        git config --global user.name "vijay-ravi"
        git add .env
        git commit -m "Update .env with AIRFLOW_IMAGE_NAME"
        git push
        
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        target-url: ${{ secrets.TARGET_URL }}
        # Such as wangchucheng
        target-username: ${{ secrets.TARGET_USERNAME }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.TARGET_TOKEN }}
